//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorHostel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_dat_giuong
    {
        public string maphieu { get; set; }
        public string magiuong { get; set; }
        public System.DateTime ngayden { get; set; }
        public Nullable<System.DateTime> ngaydi { get; set; }
    
        public virtual giuong giuong { get; set; }
        public virtual PHIEUDATGIUONG PHIEUDATGIUONG { get; set; }
    }
}
