//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorHostel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class giuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public giuong()
        {
            this.chi_tiet_dat_giuong = new HashSet<chi_tiet_dat_giuong>();
        }
    
        [DisplayName("mã giường")]
        public string magiuong { get; set; }
        [DisplayName("mã phòng")]
        public string maphong { get; set; }
        [DisplayName("mô tả")]
        public string mota { get; set; }
        [DisplayName("mã loại giường")]
        public string malg { get; set; }
        [DisplayName("tình trạng")]
        public Nullable<bool> tinhtrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_dat_giuong> chi_tiet_dat_giuong { get; set; }
        public virtual loaigiuong loaigiuong { get; set; }
        public virtual phong phong { get; set; }
        
    }
}
