//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorHostel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachhang()
        {
            this.PHIEUDATGIUONG = new HashSet<PHIEUDATGIUONG>();
        }
    
        [DisplayName("Mã khách hàng")]
        public string makh { get; set; }
        [DisplayName("Họ tên")]
        public string hoten { get; set; }
        [DisplayName("Ngày sinh")]
        public Nullable<System.DateTime> ngaysinh { get; set; }
        [DisplayName("Số điện thoại")]
        public string sdt { get; set; }
        [DisplayName("Địa chỉ")]
        public string diachi { get; set; }
        [DisplayName("Giới tính")]
        public Nullable<bool> gioitinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDATGIUONG> PHIEUDATGIUONG { get; set; }
    }
}
