//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorHostel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class loaigiuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loaigiuong()
        {
            this.giuong = new HashSet<giuong>();
        }
    
        [DisplayName("Mã loại giường")]
        public string malg { get; set; }
        [DisplayName("Tên giường")]
        public string tenlg { get; set; }
        [DisplayName("Mô tả")]
        public string mota { get; set; }
        public Nullable<int> dongia { get; set; }
        public string hinhanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giuong> giuong { get; set; }
    }
}
