//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorHostel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class PHIEUDATGIUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDATGIUONG()
        {
            this.chi_tiet_dat_giuong = new HashSet<chi_tiet_dat_giuong>();
        }

        [DisplayName("Mã Phiếu")]
        public string maphieu { get; set; }
        [DisplayName("Mã khách hàng")]
        public string makh { get; set; }
        [DisplayName("Số lượng giường")]
        public Nullable<int> soluong_giuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_dat_giuong> chi_tiet_dat_giuong { get; set; }
        public virtual khachhang khachhang { get; set; }

        
    }
}
