//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorHostel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VectorHostelEntities1 : DbContext
    {
        public VectorHostelEntities1()
            : base("name=VectorHostelEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chi_tiet_dat_giuong> chi_tiet_dat_giuong { get; set; }
        public virtual DbSet<giuong> giuong { get; set; }
        public virtual DbSet<khachhang> khachhang { get; set; }
        public virtual DbSet<loaigiuong> loaigiuong { get; set; }
        public virtual DbSet<loaiphong> loaiphong { get; set; }
        public virtual DbSet<PHIEUDATGIUONG> PHIEUDATGIUONG { get; set; }
        public virtual DbSet<phong> phong { get; set; }
    }
}
